services:
  console:
    image: console
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        BUILD_DEV: ""
    develop:
      watch:
        - action: sync
          path: ./app
          target: ./app
          ignore:
            - .env.example
        - action: rebuild
          path: ./app/.env.example
          target: ./app/.env.example
    command: tail -f /dev/null
  redis:
    image: 'redis:7.0-alpine'
    ports:
      - '6380:6379'
