version: '3'
services:
  console:
    image: console
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - '../:/app'
  redis:
    image: 'redis:7.0-alpine'
    ports:
      - '6380:6379'
